name: AppTemplate
options:
  bundleIdPrefix: com.apptemplate
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
  configs:
    Release:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

packages:
  FirebaseSDK:
    url: https://github.com/firebase/firebase-ios-sdk
    from: "11.0.0"
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: "8.0.0"
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios-spm
    from: "5.0.0"

targets:
  AppTemplate:
    type: application
    platform: iOS
    sources:
      - path: AppTemplate
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.apptemplate.app
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: AppTemplate
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        CODE_SIGN_ENTITLEMENTS: AppTemplate/AppTemplate.entitlements
    dependencies:
      - package: FirebaseSDK
        product: FirebaseAuth
      - package: FirebaseSDK
        product: FirebaseFirestore
      - package: FirebaseSDK
        product: FirebaseStorage
      - package: FirebaseSDK
        product: FirebaseAnalytics
      - package: FirebaseSDK
        product: FirebaseCrashlytics
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: RevenueCat
        product: RevenueCat
    postCompileScripts:
      - script: |
          if [ "$CONFIGURATION" = "Release" ]; then
            "${BUILD_DIR%/Build/*}/SourcePackages/checkouts/firebase-ios-sdk/Crashlytics/run"
          fi
        name: "[Firebase] Upload dSYMs"
        inputFiles:
          - $(DWARF_DSYM_FOLDER_PATH)/$(DWARF_DSYM_FILE_NAME)
          - $(DWARF_DSYM_FOLDER_PATH)/$(DWARF_DSYM_FILE_NAME)/Contents/Resources/DWARF/$(TARGET_NAME)
          - $(DWARF_DSYM_FOLDER_PATH)/$(DWARF_DSYM_FILE_NAME)/Contents/Info.plist
          - $(TARGET_BUILD_DIR)/$(INFOPLIST_PATH)
